//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IComentario.java
//  @ Date : 2019/5/23
//  @ Author : 
//
//
package Comentario;
import Publicacion.*;
import UsuarioRegistrado.*;


public interface IComentario {

}
