//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IUsuarioRegistrado.java
//  @ Date : 2019/5/23
//  @ Author : 
//
//
package UsuarioRegistrado;



public interface IUsuarioRegistrado {
	String login();

	void solicitarDatosRecuPass(String email, String Alias);

}
