//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IUsuarioLogueado.java
//  @ Date : 2019/5/23
//  @ Author : 
//
//
package UsuarioRegistrado;
import Comentario.*;
import Solicitud.*;


public interface IUsuarioLogueado {
	public void logout();
	
	public Boolean buscarOtroUsuario(String Alias);
	
	public Boolean cambiarAlias(String AliasNuevo);

	public void solicitarDatosBaja(String Pass) ;
}
