//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UsuarioLogueado.java
//  @ Date : 2019/5/23
//  @ Author : 
//
//
package UsuarioRegistrado;
import Comentario.*;
import Solicitud.*;
import Publicacion.Publicacion;
import ConexionBD.ConexionBD;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;
import java.net.URISyntaxException;
import java.net.MalformedURLException;
import java.net.URL;


public class UsuarioLogueado extends UsuarioRegistrado implements IUsuarioLogueado {
	private UsuarioRegistrado usuario;
	private SolicitudBaja Ra;
	private ArrayList<String> Rc;
	private ConexionBD conexion= new ConexionBD();

	public UsuarioLogueado(UsuarioRegistrado usuario) {
	this.usuario=usuario;
	}
	public UsuarioRegistrado getUsuario(){
		return usuario;
	};
	public void logout() {
	
	}
	
	public Boolean buscarOtroUsuario(String Alias) {
		return true;
	}
	
	public Boolean cambiarAlias(String AliasNuevo) {
		return true;
	}
	
	public void solicitarDatosBaja(String Pass) {

	}
	public void CrearPublicacion(String tipo) {
	if(tipo=="texto") {
		boolean fine=false;
		System.out.println("Escribe tu publicacion de texto:");
		Scanner sn = new Scanner(System.in);
		String opcion;
		opcion = sn.nextLine();
		if(opcion.length()<140)
			fine=true;
		else
			System.out.println("Demasiado larga.");
		if(fine) {
			Publicacion publi = new Publicacion("Texto", opcion, usuario);
			conexion.AddPublicaciones(publi.getCodPublicacion(),publi.getAlias(),0,publi.getTipo(),publi.getTexto());
			System.out.println("Publicacion publicada");
	}}
	 else if (tipo=="enlace") {
		boolean fine=false;
		System.out.println("Escribe tu URL");
		Scanner sn= new Scanner(System.in);
		String url=sn.nextLine();
			try {
				new URL(url).toURI();
				fine=true;
			}
			catch (URISyntaxException exception) {
				System.out.println("No existe");
			}
			catch (MalformedURLException exception) {
				System.out.println("Mal escrita");
			}
			if(fine) {
				Publicacion publi = new Publicacion("enlace", url, usuario);
				conexion.AddPublicaciones(publi.getCodPublicacion(),publi.getAlias(),0,publi.getTipo(),publi.getTexto());
				System.out.println("Publicacion publicada");
			}
		}
	}
	public void crearComentario(Integer idPubli){
		Boolean fine=false;
	System.out.println("Escribe tu comentario:");
	Scanner sn= new Scanner(System.in);
	String opcion=sn.nextLine();
	if(opcion.length()<140)
		fine=true;
	else
		System.out.println("Demasiado largo.");
	if(fine){
		Comentario comentario= new Comentario();
		conexion.addComentario(idPubli,comentario.getCodComentario(),usuario.getAlias(),opcion);
		}
	}
	/*
	public publicacion obtenerPublicacion(publicacion cPublicacion) {
	
	}
	
	public void eliminar(publicacion cPublicacion) {
	
	}
	*
	public void asignarSolicitudBaja(SolicitudBaja cSolicitudBaja) {
	
	}
	
	public SolicitudBaja obtenerSolicitudBaja() {
	
	}
	
	public void eliminar() {
	
	}
	
	public Comentario obtenerComentario(Comentario cComentario) {
	
	}
	
	public void asignarComentario(Comentario cComentario) {
	
	}
	
	public void eliminar(Comentario cComentario) {

	}
	*/
}
