//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ISolicitud.java
//  @ Date : 2019/5/23
//  @ Author : 
//
//
package Solicitud;



public interface ISolicitud {
	public void mandarSolicitud(Solicitud sol) ;
	public void introducirDatos(String CodSolicitud, String Alias, String email);

}
