//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SolicitudAlta.java
//  @ Date : 2019/5/23
//  @ Author : 
//
//




package Solicitud;
import UsuarioNoRegistrado.*;
import java.io.File;
import java.io.RandomAccessFile;
import java.io.IOException;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.PrintWriter;




public class SolicitudAlta extends Solicitud {
	private UsuarioNoRegistrado Rb;
	private String pass;

	public SolicitudAlta(){
	    super();
	    this.Rb=new UsuarioNoRegistrado();
	    this.pass="password";
    }

    public SolicitudAlta(String Alias, String email,UsuarioNoRegistrado visitante,String pass){
	    super(Alias,email,"SolicitudAlta");
	    this.Rb=visitante;
	    this.pass=pass;
    }

	public void asignarUsuarioNoRegistrado(UsuarioNoRegistrado cUsuarioNoRegistrado) {
        this.Rb=cUsuarioNoRegistrado;
	}

	public UsuarioNoRegistrado ObtenerUsuarioNoRegistrado(){
	    return Rb;
	}

    public void mandarSolicitud(SolicitudAlta sol) {
        try(FileWriter fw = new FileWriter("solicitudalta.txt", true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter out = new PrintWriter(bw))
        {
            out.println(sol.getCodSolicitud()+" | "+sol.getAlias()+" | "+sol.getEmail()+" | ");

        } catch (IOException e) {
            System.out.println("Error al enviar la solicitud.");
        }

    }

	public void eliminar() {

	}
}
