//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IUsuarioNoRegistrado.java
//  @ Date : 22/05/2019
//  @ Author : 
//
//
package UsuarioNoRegistrado;
import ConexionBD.ConexionBD;
import Solicitud.*;
import java.util.Scanner;
public interface IUsuarioNoRegistrado {
	String solicitarDatosAlta();
	void asignarSolicitudAlta(SolicitudAlta cSolicitudAlta) ;
}
