//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UsuarioNoRegistrado.java
//  @ Date : 22/05/2019
//  @ Author : 
//
//
package UsuarioNoRegistrado;
import java.util.Random;
import java.util.Scanner;

import ConexionBD.ConexionBD;
import Solicitud.*;


public class UsuarioNoRegistrado implements IUsuarioNoRegistrado {
	private String CodVisitante;
	private SolicitudAlta Ra;
	private ConexionBD conect=new ConexionBD();
	public UsuarioNoRegistrado(){
		this.CodVisitante="v00000";
	}

	public UsuarioNoRegistrado(String CodVisitante) {
		this.CodVisitante=CodVisitante;
		this.Ra=new SolicitudAlta();
	}
	public String solicitarDatosAlta() {
		ConexionBD conect=new ConexionBD();
		Scanner input=new Scanner(System.in);
		System.out.println("Introduzca su nuevo alias:");
		String alias=input.nextLine();
		System.out.println("Introduzca su nuevo password:");
		String pass=input.nextLine();
		System.out.println("Introduzca su emailUPM:");
		String email=input.nextLine();
                /*
                SolicitudAlta s_alta=new SolicitudAlta(alias,email,visitante,pass);
                visitante.asignarSolicitudAlta(s_alta);
                s_alta.mandarSolicitud(s_alta);
                System.out.println("Su solicitud ha sido enviada.");
                */
		if(conect.YaExiste(alias))
			System.out.println("esta cuenta ya está creada");
		else
			conect.Registrar(alias,email,pass);
		return alias;
	}
	
	public void asignarSolicitudAlta(SolicitudAlta cSolicitudAlta) {
	    this.Ra=cSolicitudAlta;
	}
	
	public SolicitudAlta ObtenerSolicitudAlta() {
        return Ra;
	}
	

	public void setCodVisitante(String CodVisitante) {
		this.CodVisitante=CodVisitante;
	}
	
	public String getCodVisitante() {
		return this.CodVisitante;
	}
	
	public void destroy() {

	}
}
